### ISSUE TITLE
JOSS review: documentation

### ISSUE THREAD

**Issue by bmcfee** [sigsep/open-unmix-paper-joss#5]
The JOSS review asks about functionality documentation.  The readme is great on this, at least from the command-line perspective.  However, I couldn't find any documentation explaining how to use programmatically.  Is there no external API for this software?

**Comment by faroit** [comment]
Thanks for mentioning this point. In fact we don't know what the best way would be to implement this.

One the one hand, we explicitly designed this as a non-package, being close to a "MNIST-style" example such as being done in [pytorch's example repo](https://github.com/pytorch/examples/tree/master/mnist). Furthermore, I don't think it is common to offer an API for the training or dataset creation. 

On the other hand users could of course interface the `test.py` (which, I guess, would be the most common thing users would want to do) but due to its simplicity of the code, instead of having a separate documentation, I would propose to:

* add a clear `inference.md/test.md` to the [`docs` folder](https://github.com/sigsep/open-unmix-pytorch/tree/master/docs)
* add docstring to the separate function
* extend the readme a bit to point to these files

We definitely plan to make a inference python package similar to [crepe](https://github.com/marl/crepe), but we want to postpone this when we released the tf version to see which version runs faster and is easier to deploy.

Would these changes be sufficient?

**Comment by bmcfee** [comment]
> Would these changes be sufficient?

Yeah, I think so.  It's reasonable enough to make the command-line API the primary interface, but it's a little unusual in python land.  As long as it's clearly documented that this is how the software is intended to be used, I think that's fine.

**Comment by faroit** [comment]
>  It's reasonable enough to make the command-line API the primary interface, but it's a little unusual in python land. 

I think non-packaged code are actually quite common for simple reference implementations. I mainly followed popular repositories such as [pytorch-CycleGAN-and-pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) which seems to hit the right spot between simple to extend and being reproducible.

> As long as it's clearly documented that this is how the software is intended to be used, I think that's fine.

* We updated `README.md` and added `/docs/inference.md` in the [latest pytorch version](https://github.com/sigsep/open-unmix-pytorch/tree/469c0742cbafb285108543a432bfaa4b6a3f0dac)

* We updated the docstrings for the separation function. See [here](https://github.com/sigsep/open-unmix-pytorch/blob/b48f377f4a42f812a2437929b498b84fbb76a827/test.py#L84-L132)

**Comment by faroit** [comment]
@bmcfee is this sufficient?

**Comment by bmcfee** [comment]
Looks great, thanks!
